spring:
  datasource:
    url: ${PG_URL}
    username: ${PG_USER}
    password: ${PG_PASS}

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080

pg:
  secret:
    password: ${PG_SECRET_PASSWORD}